name: Python CI

on:
  push:
    branches: [ main, task-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --ignore=E501,W503

    - name: Run Jupyter notebooks as tests (optional)
      run: |
        pip install nbconvert
        jupyter nbconvert --execute notebooks/data_summary.ipynb --to html --stdout
        jupyter nbconvert --execute notebooks/eda_univariate.ipynb --to html --stdout
